# kubernetes-manifests/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: movie-scraper-config
  namespace: movie-scraper
data:
  config.conf: |
    [database]
    uri = mongodb://mongodb-service:27017/
    username = root
    password = root
    db_name = movie_database

    [ui]
    host = 0.0.0.0
    port = 5000

    [backend]
    host = 0.0.0.0
    port = 5001
