# kubernetes-manifests/mongo-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prir-mongo
  namespace: movie-scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prir-mongo
  template:
    metadata:
      labels:
        app: prir-mongo
    spec:
      containers:
      - name: mongo
        image: mongo:4.4
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "root"
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: movie-scraper
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: prir-mongo
