# kubernetes-manifests/ui-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prir-ui
  namespace: movie-scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prir-ui
  template:
    metadata:
      labels:
        app: prir-ui
    spec:
      containers:
      - name: ui
        image: deefyy/ui:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_URI
          value: "mongodb://mongodb-service:27017/"
        - name: DB_USERNAME
          value: "root"
        - name: DB_PASSWORD
          value: "root"
        - name: DB_NAME
          value: "movie_database"
        - name: BACKEND_HOST
          value: "prir-backend"
        - name: BACKEND_PORT
          value: "5001"
        - name: UI_HOST
          value: "0.0.0.0"
        - name: UI_PORT
          value: "5000"

---
apiVersion: v1
kind: Service
metadata:
  name: prir-ui
  namespace: movie-scraper
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: prir-ui
